### ISSUE TITLE
failed to run flow/app.go

### ISSUE THREAD

**Issue by chairwa** [yomorun/yomo-wasmedge-tensorflow#10]
use WasmEdge v0.10.0 with github.com/second-state/WasmEdge-go v0.10.0,

cd flow
go run --tags "tensorflow image" app.go
\# github.com/second-state/wasmedge-bindgen/host/go
../../../go/pkg/mod/github.com/second-state/wasmedge-bindgen@v0.1.14/host/go/bindgen.go:43:24: undefined: wasmedge.ImportObject
../../../go/pkg/mod/github.com/second-state/wasmedge-bindgen@v0.1.14/host/go/bindgen.go:61:26: undefined: wasmedge.NewImportObject
../../../go/pkg/mod/github.com/second-state/wasmedge-bindgen@v0.1.14/host/go/bindgen.go:68:7: b.vm.RegisterImport undefined (type *wasmedge.VM has no field or method RegisterImport)
../../../go/pkg/mod/github.com/second-state/wasmedge-bindgen@v0.1.14/host/go/bindgen.go:84:28: b.vm.GetStore().FindMemory undefined (type *wasmedge.Store has no field or method FindMemory)
../../../go/pkg/mod/github.com/second-state/wasmedge-bindgen@v0.1.14/host/go/bindgen.go:184:28: b.vm.GetStore().FindMemory undefined (type *wasmedge.Store has no field or method FindMemory)
../../../go/pkg/mod/github.com/second-state/wasmedge-bindgen@v0.1.14/host/go/bindgen.go:261:28: b.vm.GetStore().FindMemory undefined (type *wasmedge.Store has no field or method FindMemory)

**Comment by DarumaDocker** [comment]
Please try to wasmedge-bindgen@v0.2.1

**Comment by Alps-Sun** [comment]
failed to "go run --tags "tensorflow image" app.go"
use wasmege  0.12.1

# go run --tags "tensorflow image" app.go
# github.com/second-state/WasmEdge-go/wasmedge
/root/go/pkg/mod/github.com/second-state/!wasm!edge-go@v0.12.0/wasmedge/ast.go:3:11: fatal error: wasmedge/wasmedge.h: No such file or directory
    3 | // #include <wasmedge/wasmedge.h>
      |           ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

**Comment by Alps-Sun** [comment]
Has been resolved!
