### ISSUE TITLE
yolov5 tflite model output

### ISSUE THREAD

**Issue by alps-sun** [yomorun/yomo-wasmedge-tensorflow#15]
How can I get the output of yolov5 tflite model through "get_output<T: TensorType>(&self, name: &str)" 

```rust
let model_data: &[u8] = include_bytes!("yolov5s_counter.tflite");
let labels = include_str!("classes.txt");
let flat_img = wasmedge_tensorflow_interface::load_jpg_image_to_rgb8(&image_data[..], 192, 192);
let output_tensor = session.get_output("output");
```

what should i do

**Comment by wujunzhuo** [comment]
This is more or less related to the wasmedge tensorflow Rust interface API. Could you provide the URLs of tflite model file and class labels file?

**Comment by alps-sun** [comment]
solved
