### ISSUE TITLE
wasmedge performance data

### ISSUE THREAD

**Issue by alps-sun** [yomorun/yomo-wasmedge-tensorflow#16]
# ENV
Ubuntu 
VERSION="20.04 LTS (Focal Fossa)"

I want to collect the following Wasmedge Runtime performance data when yomo-wasmedge-tensorflow is running, such as CPU, Mem, etc. How can I do it

**Comment by zihan987** [comment]
To collect performance data when yomo-wasmedge-tensorflow is running, you can do the following:
1. Install a system monitoring tool like the "top" command or "htop". These tools can show you real-time CPU, memory, and network usage information.
2. Run the "top" or "htop" command while yomo-wasmedge-tensorflow is running. You will be able to see the CPU% and MEM% being used by the tensorflow process.
3. Alternatively, you can install a monitoring agent like Prometheus to collect metrics. You can write an exporter to expose metrics from yomo-wasmedge-tensorflow like:
 - CPU usage
 - Memory usage
 - Number of requests served
 - Latency of requests
Prometheus will then scrape these metrics periodically and you can visualize them using Grafana.
4. You can also log the performance data programmatically from within yomo-wasmedge-tensorflow using the psutil library. Call psutil functions periodically to get the CPU% and memory usage, and log the values to a file.
5. Finally, you can write a small script to profile yomo-wasmedge-tensorflow using cProfile. Run the script while it's running to collect performance data like:
 - Number of function calls 
- Total runtime 
- Function-wise times

**Comment by alps-sun** [comment]
> 

Thank you, I solved this problem using htop and psutil
