### ISSUE TITLE
I would like to consult how to run yomo-wasmedge-tensorflow in docker

### ISSUE THREAD

**Issue by alps-sun** [yomorun/yomo-wasmedge-tensorflow#17]
I would like to consult how to run yomo-wasmedge-tensorflow in docker, or is there a docker image for this project

thank you

**Comment by fanweixiao** [comment]
Hi @alps-sun, currently we do not have a docker build, you can implement yours.
btw, can I invite you to [YoMo community](https://discord.gg/2drpN4pa)?
