### ISSUE TITLE
Connect to zipper failure: yomo: read unexpected frame during waiting authentication resp, frame read: RejectedFrame

### ISSUE THREAD

**Issue by alps-sun** [yomorun/yomo-wasmedge-tensorflow#20]
when i execute the following command:

` yomo serve -c ./zipper/config.yaml`
log:
`ℹ️   Running YoMo-Zipper...
time=2024-01-04T17:00:45.711+08:00 level=INFO msg="using config file" component=zipper zipper_name=Service file_path=./zipper/config.yaml
time=2024-01-04T17:00:45.711+08:00 level=INFO msg="Listening SIGUSR1, SIGUSR2, SIGTERM/SIGINT..."
time=2024-01-04T17:00:45.712+08:00 level=INFO msg="zipper is up and running" component=zipper zipper_name=Service zipper_addr=[::]:9900 pid=238349 quic="[v1 v2]" auth_name=[none]`

but execute the following command
`go run -tags tensorflowlite,image app.go`

`time=2024-01-04T17:01:59.215+08:00 level=INFO msg="use credential" component=StreamFunction client_id=c2pHJpp6yZBcGbkWK_KtC client_name=inference credential_name=none
time=2024-01-04T17:01:59.219+08:00 level=ERROR msg="can not connect to zipper" component=StreamFunction client_id=c2pHJpp6yZBcGbkWK_KtC client_name=inference zipper_addr=127.0.0.1:9900 err="yomo: read unexpected frame during waiting authentication resp, frame read: RejectedFrame"
2024/01/04 17:01:59 ❌ Connect to zipper failure: yomo: read unexpected frame during waiting authentication resp, frame read: RejectedFrame
exit status 1
`

` yomo serve -c ./zipper/config.yaml`  log:

`time=2024-01-04T17:01:59.219+08:00 level=ERROR msg="handshake failed" component=zipper zipper_name=Service err="frame: cannot new a frame from \x03"`

what should i do ? thx

**Comment by Yoname** [comment]
https://thinhdanggroup.github.io/function-calling-openai/
这篇文章写了当前开发者用open AI 的function-calling 需要自己处理的一些问题

**Comment by fanweixiao** [comment]
Hi @alps-sun, fixed, please try again.

**Comment by alps-sun** [comment]
I would like to ask, if i need to reinstall yomo v1.13.0 version, there is a command code similar to 
`curl -fsSL "https://get.yomo.run" | sh  -v 1.13.0`

**Comment by fanweixiao** [comment]
> I would like to ask, if i need to reinstall yomo v1.13.0 version, there is a command code similar to `curl -fsSL "https://get.yomo.run" | sh -v 1.13.0`

Oh, currently the script doesn't support this, you have to download here: https://github.com/yomorun/yomo/releases/tag/v1.13.0

**Comment by alps-sun** [comment]
thank you!  
Excuse me, I still have some problems here. The versions I use have always been yomo v1.13.0 and wasmedge v0.12.1, but now the same code runs in the environment of reinstalling yomo v1.13.0 and wasmedge v0.12.1 but the following problems occur.

yomo serve -c ./zipper/config.yaml
`ℹ️   Running YoMo-Zipper...
time=2024-01-12T16:34:22.172+08:00 level=INFO msg="using config file" component=zipper zipper_name=Service file_path=./zipper/config.yaml
time=2024-01-12T16:34:22.172+08:00 level=INFO msg="Listening SIGUSR1, SIGUSR2, SIGTERM/SIGINT..."
time=2024-01-12T16:34:22.174+08:00 level=INFO msg="zipper is up and running" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 pid=683589 quic="[draft-29 v1 v2]" auth_name=[none]

time=2024-01-12T16:34:32.359+08:00 level=INFO msg="client alpn proto" component=zipper proto=yomo
time=2024-01-12T16:34:32.359+08:00 level=INFO msg="connection connected" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36160 local_addr=127.0.0.1:9900
time=2024-01-12T16:34:37.707+08:00 level=INFO msg="client alpn proto" component=zipper proto=yomo
time=2024-01-12T16:34:37.708+08:00 level=INFO msg="connection connected" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36369 local_addr=127.0.0.1:9900
time=2024-01-12T16:34:37.960+08:00 level=INFO msg="routing data frame" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36369 local_addr=127.0.0.1:9900 stream_id=-yLpokAzkFCwvQDkyKISZ stream_name=surface-detect stream_type=Source from_stream_name=surface-detect from_stream_id=-yLpokAzkFCwvQDkyKISZ to_stream_name=surface-detect to_stream_id=iecazaTkpjtTQ9zu3CM7L data_frame="tid=sSSrVtjcqkXWhhymlWZ0b | tag=0x10 | source=-yLpokAzkFCwvQDkyKISZ | data[25145]=0xff 0xd8 0xff 0xdb 0x00 0x84 0x00 0x02 0x01 0x01 0x01 0x01 0x01 0x02 0x01 0x01"
time=2024-01-12T16:34:37.983+08:00 level=INFO msg="routing data frame" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36369 local_addr=127.0.0.1:9900 stream_id=-yLpokAzkFCwvQDkyKISZ stream_name=surface-detect stream_type=Source from_stream_name=surface-detect from_stream_id=-yLpokAzkFCwvQDkyKISZ to_stream_name=surface-detect to_stream_id=iecazaTkpjtTQ9zu3CM7L data_frame="tid=pWsQDYUDGQmP6KqD0XtfM | tag=0x10 | source=-yLpokAzkFCwvQDkyKISZ | data[25145]=0xff 0xd8 0xff 0xdb 0x00 0x84 0x00 0x02 0x01 0x01 0x01 0x01 0x01 0x02 0x01 0x01"
time=2024-01-12T16:34:38.029+08:00 level=INFO msg="routing data frame" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36369 local_addr=127.0.0.1:9900 stream_id=-yLpokAzkFCwvQDkyKISZ stream_name=surface-detect stream_type=Source from_stream_name=surface-detect from_stream_id=-yLpokAzkFCwvQDkyKISZ to_stream_name=surface-detect to_stream_id=iecazaTkpjtTQ9zu3CM7L data_frame="tid=EXOzWhfXzPrcT1tI55pt0 | tag=0x10 | source=-yLpokAzkFCwvQDkyKISZ | data[25145]=0xff 0xd8 0xff 0xdb 0x00 0x84 0x00 0x02 0x01 0x01 0x01 0x01 0x01 0x02 0x01 0x01"
time=2024-01-12T16:34:38.063+08:00 level=INFO msg="routing data frame" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36369 local_addr=127.0.0.1:9900 stream_id=-yLpokAzkFCwvQDkyKISZ stream_name=surface-detect stream_type=Source from_stream_name=surface-detect from_stream_id=-yLpokAzkFCwvQDkyKISZ to_stream_name=surface-detect to_stream_id=iecazaTkpjtTQ9zu3CM7L data_frame="tid=_-GI8T7OcGnV20M-Ri1cR | tag=0x10 | source=-yLpokAzkFCwvQDkyKISZ | data[7829]=0xff 0xd8 0xff 0xdb 0x00 0x84 0x00 0x02 0x01 0x01 0x01 0x01 0x01 0x02 0x01 0x01"
time=2024-01-12T16:34:38.095+08:00 level=INFO msg="routing data frame" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36369 local_addr=127.0.0.1:9900 stream_id=-yLpokAzkFCwvQDkyKISZ stream_name=surface-detect stream_type=Source from_stream_name=surface-detect from_stream_id=-yLpokAzkFCwvQDkyKISZ to_stream_name=surface-detect to_stream_id=iecazaTkpjtTQ9zu3CM7L data_frame="tid=qKpbGkvXu_jxHbiHpJA9C | tag=0x10 | source=-yLpokAzkFCwvQDkyKISZ | data[7829]=0xff 0xd8 0xff 0xdb 0x00 0x84 0x00 0x02 0x01 0x01 0x01 0x01 0x01 0x02 0x01 0x01"
time=2024-01-12T16:34:38.180+08:00 level=INFO msg="routing data frame" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36369 local_addr=127.0.0.1:9900 stream_id=-yLpokAzkFCwvQDkyKISZ stream_name=surface-detect stream_type=Source from_stream_name=surface-detect from_stream_id=-yLpokAzkFCwvQDkyKISZ to_stream_name=surface-detect to_stream_id=iecazaTkpjtTQ9zu3CM7L data_frame="tid=8S0EO7ytrAIsk3-F0SjPs | tag=0x10 | source=-yLpokAzkFCwvQDkyKISZ | data[22861]=0xff 0xd8 0xff 0xdb 0x00 0x84 0x00 0x02 0x01 0x01 0x01 0x01 0x01 0x02 0x01 0x01"
time=2024-01-12T16:34:38.186+08:00 level=INFO msg="routing data frame" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36369 local_addr=127.0.0.1:9900 stream_id=-yLpokAzkFCwvQDkyKISZ stream_name=surface-detect stream_type=Source from_stream_name=surface-detect from_stream_id=-yLpokAzkFCwvQDkyKISZ to_stream_name=surface-detect to_stream_id=iecazaTkpjtTQ9zu3CM7L data_frame="tid=Tw8VTXPCUAtm9Gp7aVHgO | tag=0x10 | source=-yLpokAzkFCwvQDkyKISZ | data[22861]=0xff 0xd8 0xff 0xdb 0x00 0x84 0x00 0x02 0x01 0x01 0x01 0x01 0x01 0x02 0x01 0x01"
time=2024-01-12T16:34:38.269+08:00 level=INFO msg="routing data frame" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36369 local_addr=127.0.0.1:9900 stream_id=-yLpokAzkFCwvQDkyKISZ stream_name=surface-detect stream_type=Source from_stream_name=surface-detect from_stream_id=-yLpokAzkFCwvQDkyKISZ to_stream_name=surface-detect to_stream_id=iecazaTkpjtTQ9zu3CM7L data_frame="tid=CEFOckWjAGkIxm2dlCeiv | tag=0x10 | source=-yLpokAzkFCwvQDkyKISZ | data[22861]=0xff 0xd8 0xff 0xdb 0x00 0x84 0x00 0x02 0x01 0x01 0x01 0x01 0x01 0x02 0x01 0x01"
time=2024-01-12T16:34:38.330+08:00 level=INFO msg="routing data frame" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36369 local_addr=127.0.0.1:9900 stream_id=-yLpokAzkFCwvQDkyKISZ stream_name=surface-detect stream_type=Source from_stream_name=surface-detect from_stream_id=-yLpokAzkFCwvQDkyKISZ to_stream_name=surface-detect to_stream_id=iecazaTkpjtTQ9zu3CM7L data_frame="tid=dwkTLoGZP0dtEsPm80RCF | tag=0x10 | source=-yLpokAzkFCwvQDkyKISZ | data[8930]=0xff 0xd8 0xff 0xdb 0x00 0x84 0x00 0x02 0x01 0x01 0x01 0x01 0x01 0x02 0x01 0x01"
time=2024-01-12T16:34:38.381+08:00 level=INFO msg="routing data frame" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36369 local_addr=127.0.0.1:9900 stream_id=-yLpokAzkFCwvQDkyKISZ stream_name=surface-detect stream_type=Source from_stream_name=surface-detect from_stream_id=-yLpokAzkFCwvQDkyKISZ to_stream_name=surface-detect to_stream_id=iecazaTkpjtTQ9zu3CM7L data_frame="tid=GpaphrH-5b9ELii8P-hfY | tag=0x10 | source=-yLpokAzkFCwvQDkyKISZ | data[8930]=0xff 0xd8 0xff 0xdb 0x00 0x84 0x00 0x02 0x01 0x01 0x01 0x01 0x01 0x02 0x01 0x01"
**_time=2024-01-12T16:34:47.482+08:00 level=ERROR msg="connection closed" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36160 local_addr=127.0.0.1:9900 err=EOF_**
time=2024-01-12T16:34:47.481+08:00 level=WARN msg="data stream closed" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36160 local_addr=127.0.0.1:9900 stream_id=iecazaTkpjtTQ9zu3CM7L stream_name=surface-detect stream_type=StreamFunction err_code=NetClosed error="use of closed network connection"
time=2024-01-12T16:34:49.537+08:00 level=WARN msg="data stream closed" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36369 local_addr=127.0.0.1:9900 stream_id=-yLpokAzkFCwvQDkyKISZ stream_name=surface-detect stream_type=Source err_code=NetClosed error="use of closed network connection"
**_time=2024-01-12T16:34:49.537+08:00 level=ERROR msg="connection closed" component=zipper zipper_name=Service zipper_addr=0.0.0.0:9900 remote_addr=127.0.0.1:36369 local_addr=127.0.0.1:9900 err=EOF_**
`

go run -tags tensorflowlite,image app.go
`time=2024-01-12T16:29:13.533+08:00 level=INFO msg="use credential" component=StreamFunction client_id=5MYDj_nLFdo0-x_4zfpdA client_name=surface-detect credential_name=none
time=2024-01-12T16:29:13.537+08:00 level=INFO msg="connected to zipper" component=StreamFunction client_id=5MYDj_nLFdo0-x_4zfpdA client_name=surface-detect zipper_addr=localhost:9900

RUST: Loaded image in ... 36.860113ms
RUST: Loaded image in ... 68.102833ms
RUST: Loaded image in ... 40.453069ms
RUST: Loaded image in ... 50.491154ms
RUST: Loaded image in ... 72.075931ms
RUST: Loaded image in ... 142.638338ms
RUST: Loaded image in ... 76.604568ms
RUST: Loaded image in ... 154.786232ms
RUST: Loaded image in ... 30.719779ms
RUST: Loaded image in ... 65.109929ms

time=2024-01-12T16:29:26.836+08:00 level=ERROR msg="client err" component=StreamFunction client_id=5MYDj_nLFdo0-x_4zfpdA client_name=surface-detect err="timeout: no recent network activity"
time=2024-01-12T16:29:35.859+08:00 level=ERROR msg="reconnect error" component=StreamFunction client_id=5MYDj_nLFdo0-x_4zfpdA client_name=surface-detect zipper_addr=localhost:9900 err="timeout: no recent network activity"
signal: killed
`
I would like to ask what the reason is, thank you
