### ISSUE TITLE
lite-model_aiy_vision_classifier_food_V1_1.tflite file not exist

### ISSUE THREAD

**Issue by yixingjia** [yomorun/yomo-wasmedge-tensorflow#7]
In the latest code flow/rust_mobilenet_food/src/lib.rs line 9 it try to load the model file lite-model_aiy_vision_classifier_food_V1_1.tflite but this file doens't exsit. In v0.2.0 release, the file  name is rust_mobilenet_food_lib_bg.so and can be downloaded at the download page.

**Comment by juntao** [comment]
You can try this one for the time being:

https://github.com/second-state/wasm-learning/tree/master/cli/tflite/src/models/mobilenet_v1_1.0_224

**Comment by yixingjia** [comment]
@juntao  Thank You! I work around it by get one  from https://tfhub.dev/google/lite-model/aiy/vision/classifier/food_V1/1?lite-format=tflite
