### ISSUE TITLE
Can this demo code works with other TFlite models from TensorFlow Hub?

### ISSUE THREAD

**Issue by yixingjia** [yomorun/yomo-wasmedge-tensorflow#9]
I have tried to play with other modules like https://tfhub.dev/google/lite-model/aiy/vision/classifier/insects_V1/3 and https://tfhub.dev/google/aiy/vision/classifier/plants_V1/1  and I recompile the code with rustwasmc , when try to infer it always say 

RUST: Loaded image in ... 16.25169ms
**RUST: index -1, prob 0**
RUST: Finished post-processing in ... 268.088698ms

the modify part for lib.rs as follow
``` 
session.add_input("input", &flat_img, &[1, 192, 192, 3])
       .add_output("MobilenetV2/Predictions/Softmax")
       .run();
let res_vec: Vec<f32> = session.get_output("MobilenetV2/Predictions/Softmax");
```

Seems it only works for the food module?

**Comment by yixingjia** [comment]
the modify part for lib.rs as follow
``` 
session.add_input("input", &flat_img, &[1, 192, 192, 3])
       .add_output("MobilenetV2/Predictions/Softmax")
       .run();
let res_vec: Vec<f32> = session.get_output("MobilenetV2/Predictions/Softmax");
```

**Comment by juntao** [comment]
The tensor names for each model is different. Here are the names for insect model we used. (It is frozen PB not TFLITE, however). They are very different from the food model.

https://github.com/second-state/WasmEdge-go-examples/blob/master/go_MobilenetInsects/rust_mobilenet_insects/src/lib.rs

Also, I think you could use AOT binary for your example. It will run 10x faster.

**Comment by yixingjia** [comment]
Thanks You! @juntao  That works.
